server:
  port: 8088

# 数据库配置；启动时配置数据库资源信息
spring:
  application:
    name: trigger-task-demo
  config:
    name: trigger-task-demo
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://127.0.0.1:3306/trigger-task-demo?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver

# Redis
redis:
  sdk:
    config:
      host: 127.0.0.1
      port: 6379
      password: 12345678
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.datasource.DataSourceUtils: DEBUG